import React from "react";

const BooksReleased = () => {
  const books = [
    {
      author: "Alfred D\u00f6blin",
      country: "Germany",
      imageLink: "images/berlin-alexanderplatz.jpg",
      language: "German",
      link: "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
      pages: 600,
      title: "Berlin Alexanderplatz",
      year: 1929,
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "images/crime-and-punishment.jpg",
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
      pages: 551,
      title: "Crime and Punishment",
      year: 1866,
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "images/the-idiot.jpg",
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/The_Idiot\n",
      pages: 656,
      title: "The Idiot",
      year: 1869,
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "images/the-possessed.jpg",
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
      pages: 768,
      title: "The Possessed",
      year: 1872,
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "images/the-brothers-karamazov.jpg",
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
      pages: 824,
      title: "The Brothers Karamazov",
      year: 1880,
    },
    {
      author: "George Eliot",
      country: "United Kingdom",
      imageLink: "images/middlemarch.jpg",
      language: "English",
      link: "https://en.wikipedia.org/wiki/Middlemarch\n",
      pages: 800,
      title: "Middlemarch",
      year: 1871,
    },
    {
      author: "Ralph Ellison",
      country: "United States",
      imageLink: "images/invisible-man.jpg",
      language: "English",
      link: "https://en.wikipedia.org/wiki/Invisible_Man\n",
      pages: 581,
      title: "Invisible Man",
      year: 1952,
    },
    {
      author: "Euripides",
      country: "Greece",
      imageLink: "images/medea.jpg",
      language: "Greek",
      link: "https://en.wikipedia.org/wiki/Medea_(play)\n",
      pages: 104,
      title: "Medea",
      year: -431,
    },
    {
      author: "William Faulkner",
      country: "United States",
      imageLink: "images/absalom-absalom.jpg",
      language: "English",
      link: "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
      pages: 313,
      title: "Absalom, Absalom!",
      year: 1936,
    },
    {
      author: "William Faulkner",
      country: "United States",
      imageLink: "images/the-sound-and-the-fury.jpg",
      language: "English",
      link: "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
      pages: 326,
      title: "The Sound and the Fury",
      year: 1929,
    },
    {
      author: "Gustave Flaubert",
      country: "France",
      imageLink: "images/madame-bovary.jpg",
      language: "French",
      link: "https://en.wikipedia.org/wiki/Madame_Bovary\n",
      pages: 528,
      title: "Madame Bovary",
      year: 1857,
    },
    
  ];
  return <div>BooksReleased</div>;
};

export default BooksReleased;
